POST http://localhost:3000/message
Content-Type: application/json

{
    "phone": "5599984825723",
    "name": "Teste",
    "trigger": "LEMBRETE",
    "date": "22/01",
    "time": "14:00",
    "barber": "Frank"
}