<?php

namespace Database\Seeders;

use App\Models\Barbershop;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;


class BarbershopSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $barbershops = [
            [
                'name' => 'Alpha Barber',
                'slug' => 'alpha-barber',
                'phone' => '(11) 99999-0001',
                'email' => 'contato@alphabarber.com',
                'zip_code' => '01001-000',
                'street' => 'Rua das Palmeiras',
                'number' => '120',
                'complement' => null,
                'neighborhood' => 'Centro',
                'city' => 'São Paulo',
                'state' => 'SP',
                'logo_path' => null,
                'opening_time' => '08:00:00',
                'closing_time' => '19:00:00',
                'whatsapp' => '(11) 98888-0001',
                'instagram' => '@alphabarber',
                'website' => 'https://alphabarber.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'premium',
                'subscription_ends_at' => '2027-07-21',
                'active' => true,
            ],
            [
                'name' => 'King Barber',
                'slug' => 'king-barber',
                'phone' => '(21) 99999-0002',
                'email' => 'contato@kingbarber.com',
                'zip_code' => '20010-000',
                'street' => 'Av. Brasil',
                'number' => '450',
                'complement' => null,
                'neighborhood' => 'Centro',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'logo_path' => null,
                'opening_time' => '09:00:00',
                'closing_time' => '20:00:00',
                'whatsapp' => '(21) 98888-0002',
                'instagram' => '@kingbarber',
                'website' => 'https://kingbarber.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'basic',
                'subscription_ends_at' => '2027-03-15',
                'active' => true,
            ],
            [
                'name' => 'Old School Barber',
                'slug' => 'old-school-barber',
                'phone' => '(31) 99999-0003',
                'email' => 'contato@oldschool.com',
                'zip_code' => '30110-000',
                'street' => 'Rua Bahia',
                'number' => '85',
                'complement' => null,
                'neighborhood' => 'Funcionários',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'logo_path' => null,
                'opening_time' => '08:30:00',
                'closing_time' => '18:30:00',
                'whatsapp' => '(31) 98888-0003',
                'instagram' => '@oldschoolbarber',
                'website' => 'https://oldschoolbarber.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'free',
                'subscription_ends_at' => null,
                'active' => true,
            ],
            [
                'name' => 'Barbearia Império',
                'slug' => 'barbearia-imperio',
                'phone' => '(41) 99999-0004',
                'email' => 'contato@imperio.com',
                'zip_code' => '80010-000',
                'street' => 'Rua XV de Novembro',
                'number' => '250',
                'complement' => null,
                'neighborhood' => 'Centro',
                'city' => 'Curitiba',
                'state' => 'PR',
                'logo_path' => null,
                'opening_time' => '08:00:00',
                'closing_time' => '19:30:00',
                'whatsapp' => '(41) 98888-0004',
                'instagram' => '@barbeariaimperio',
                'website' => 'https://barbeariaimperio.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'premium',
                'subscription_ends_at' => '2028-01-01',
                'active' => true,
            ],
            [
                'name' => 'Dom Barber',
                'slug' => 'dom-barber',
                'phone' => '(51) 99999-0005',
                'email' => 'contato@dombarber.com',
                'zip_code' => '90010-000',
                'street' => 'Rua dos Andradas',
                'number' => '540',
                'complement' => null,
                'neighborhood' => 'Centro Histórico',
                'city' => 'Porto Alegre',
                'state' => 'RS',
                'logo_path' => null,
                'opening_time' => '09:00:00',
                'closing_time' => '20:00:00',
                'whatsapp' => '(51) 98888-0005',
                'instagram' => '@dombarber',
                'website' => 'https://dombarber.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'basic',
                'subscription_ends_at' => '2027-10-10',
                'active' => true,
            ],
            [
                'name' => 'Barber Prime',
                'slug' => 'barber-prime',
                'phone' => '(71) 99999-0006',
                'email' => 'contato@barberprime.com',
                'zip_code' => '40010-000',
                'street' => 'Av. Sete de Setembro',
                'number' => '310',
                'complement' => null,
                'neighborhood' => 'Centro',
                'city' => 'Salvador',
                'state' => 'BA',
                'logo_path' => null,
                'opening_time' => '08:00:00',
                'closing_time' => '19:00:00',
                'whatsapp' => '(71) 98888-0006',
                'instagram' => '@barberprime',
                'website' => 'https://barberprime.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'free',
                'subscription_ends_at' => null,
                'active' => true,
            ],
            [
                'name' => 'Corte Fino',
                'slug' => 'corte-fino',
                'phone' => '(81) 99999-0007',
                'email' => 'contato@cortefino.com',
                'zip_code' => '50010-000',
                'street' => 'Rua Aurora',
                'number' => '112',
                'complement' => null,
                'neighborhood' => 'Boa Vista',
                'city' => 'Recife',
                'state' => 'PE',
                'logo_path' => null,
                'opening_time' => '08:30:00',
                'closing_time' => '19:30:00',
                'whatsapp' => '(81) 98888-0007',
                'instagram' => '@cortefino',
                'website' => 'https://cortefino.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'basic',
                'subscription_ends_at' => '2027-09-01',
                'active' => true,
            ],
            [
                'name' => 'Black Beard',
                'slug' => 'black-beard',
                'phone' => '(61) 99999-0008',
                'email' => 'contato@blackbeard.com',
                'zip_code' => '70010-000',
                'street' => 'SQS 308',
                'number' => '15',
                'complement' => null,
                'neighborhood' => 'Asa Sul',
                'city' => 'Brasília',
                'state' => 'DF',
                'logo_path' => null,
                'opening_time' => '09:00:00',
                'closing_time' => '20:00:00',
                'whatsapp' => '(61) 98888-0008',
                'instagram' => '@blackbeard',
                'website' => 'https://blackbeard.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'premium',
                'subscription_ends_at' => '2027-12-31',
                'active' => true,
            ],
            [
                'name' => 'Elite Barber',
                'slug' => 'elite-barber',
                'phone' => '(85) 99999-0009',
                'email' => 'contato@elitebarber.com',
                'zip_code' => '60010-000',
                'street' => 'Av. Beira Mar',
                'number' => '890',
                'complement' => null,
                'neighborhood' => 'Meireles',
                'city' => 'Fortaleza',
                'state' => 'CE',
                'logo_path' => null,
                'opening_time' => '08:00:00',
                'closing_time' => '19:00:00',
                'whatsapp' => '(85) 98888-0009',
                'instagram' => '@elitebarber',
                'website' => 'https://elitebarber.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'basic',
                'subscription_ends_at' => '2027-08-20',
                'active' => true,
            ],
            [
                'name' => 'Premium Barber Shop',
                'slug' => 'premium-barber-shop',
                'phone' => '(27) 99999-0010',
                'email' => 'contato@premiumbarber.com',
                'zip_code' => '29010-000',
                'street' => 'Av. Vitória',
                'number' => '650',
                'complement' => null,
                'neighborhood' => 'Centro',
                'city' => 'Vitória',
                'state' => 'ES',
                'logo_path' => null,
                'opening_time' => '09:00:00',
                'closing_time' => '21:00:00',
                'whatsapp' => '(27) 98888-0010',
                'instagram' => '@premiumbarbershop',
                'website' => 'https://premiumbarbershop.com.br',
                'timezone' => 'America/Sao_Paulo',
                'subscription_plan' => 'premium',
                'subscription_ends_at' => '2028-07-21',
                'active' => true,
            ],
        ];

        foreach ($barbershops as $barbershop) {
            Barbershop::create($barbershop);
        }

    }
}
